package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class previewController {
	@FXML
	private TextField fname;
	@FXML
	private TextField midinit;
	@FXML
	private TextField lname;

	// Event Listener on Button.onAction
	@FXML
	public void btnSubmitClicked(ActionEvent event) {
		// TODO Autogenerated
		String f_name = fname.getText();
		String mid_init = midinit.getText();
		String l_name = lname.getText();
		System.out.print("Your name is: " + f_name + " " + mid_init + " " + l_name);
	}
}
